server:
  port: 8081
  servlet:
    context-path: /mybatis

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thymeleaf
    username: root
    password: 1234